apiVersion: v1 
kind: Service 
metadata: 
  name: workshop-service 
  namespace: automotive-workshop 
spec: 
  selector: 
    app: workshop 
  ports: 
  - protocol: TCP 
    port: 8000 
    targetPort: 8000 
